name: salutation sur un jour quelconque
on: workflow_dispatch
env:
  DAY_OF_WEEK: Lundi ## Variable d'environnement pour l'ensemble du flux de travail

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Salut ## Variable d'environnement pour la tâche
    steps:
      - name: "Dites Salut Mona nous sommes lundi"
        run: echo "$Greeting $First_Name. Nous sommes $DAY_OF_WEEK!"
        env:
          First_Name: Mona ## Variable d'environnement uniquement pour l'étape "Dites Salut Mona nous sommes lundi" de la tâche "greeting_job"
        
      - name: Test Variable Environnement
        run: echo "ENV_VARIABLE = ${{ vars.ENV_VARIABLE }} ---- ENV_SECRET = ${{ secrets.ENV_SECRET }}"

      - name: Test variable de Repository
        run: echo "REPO_VARIABLE = ${{REPO_VARIABLE}} ou ${{vars.REPO_VARIABLE}}  ----- REPO_SECRET = ${{REPO_SECRET}} ou ${{secrets.REPO_SECRET}}"